=== Quarren/XML_puissance4/projet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

	<xsd:element name="grille">	
		<xsd:complexType>
			<xsd:sequence minOccurs="7" maxOccurs="7">
				<xsd:element name="colonne">
					<xsd:complexType>
						<xsd:sequence minOccurs="6" maxOccurs="6">
							<xsd:element name="ligne">
								<xsd:complexType>
									<xsd:attribute name="joueur">
										<xsd:simpleType>
											<xsd:restriction base="xsd:string">
												<xsd:enumeration value="jaune" />
												<xsd:enumeration value="rouge" />
											</xsd:restriction>
										</xsd:simpleType>
									</xsd:attribute>
									<xsd:attribute name="coup" type="xsd:integer"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== Quarren/XML_puissance4/situation2.xml
<?xml version="1.0" encoding="UTF-8"?>
<grille
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="projet.xsd
">
	<colonne>
		<ligne/>
		<ligne />
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
	</colonne>
	<colonne>
		<ligne joueur="jaune" coup="2"/>
		<ligne joueur="jaune" coup="4"/>
		<ligne joueur="jaune" coup="8"/>
		<ligne joueur="jaune" coup="10"/>
		<ligne/>
		<ligne/>
	</colonne>
	<colonne>
		<ligne joueur="rouge" coup="1"/>
		<ligne joueur="rouge" coup="3"/>
		<ligne joueur="rouge" coup="5"/>
		<ligne joueur="jaune" coup="6"/>
		<ligne/>
		<ligne/>
	</colonne>
	<colonne>
		<ligne joueur="rouge" coup="7"/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
	</colonne>
	<colonne>
		<ligne joueur="rouge" coup="9"/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
	</colonne>
	<colonne>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
	</colonne>
	<colonne>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
	</colonne>
</grille>

=== Quarren/XML_puissance4/situation1.xml
<?xml version="1.0" encoding="UTF-8"?>
<grille
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="projet.xsd
">
	<colonne>
		<ligne/>
		<ligne />
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
	</colonne>
	<colonne>
		<ligne joueur="X" coup="2"/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
	</colonne>
	<colonne>
		<ligne joueur="O" coup="1"/>
		<ligne joueur="O" coup="3"/>
		<ligne joueur="O" coup="5"/>
		<ligne joueur="O" coup="7"/>
		<ligne/>
		<ligne/>
	</colonne>
	<colonne>
		<ligne joueur="X" coup="4"/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
	</colonne>
	<colonne>
		<ligne joueur="X" coup="6"/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
	</colonne>
	<colonne>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
	</colonne>
	<colonne>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
		<ligne/>
	</colonne>
	</grille>
